application:
  chart_path: deploy
  secret_ref:
    namespace: gabbar-build
    name: git-auth-forked
  namespaceLabels:
    label: value
    stakater.com/tenant: alpha
    owner: stakater
  values_from:
  - configMapKeyRef:
      name: default-values
      namespace: my-ns
      key: values.yaml
      optional: false
  value_overrides:
    application:
      deployment:
        image:
          repository: {{APPLICATION_IMAGE_NAME}}
          tag: {{APPLICATION_IMAGE_TAG}}
