application:
  chart_path: deploy
  secret_ref:
    namespace: gabbar-build
    name: git-auth-forked
  namespaceLabels:
    label: value
    stakater.com/tenant: alpha
    owner: stakater
  values_from:
  - secretKeyRef:
      name: nordmart-bot
      namespace: stakater-tronador
      key: password
  - secretKeyRef:
      name: nordmart-bot
      namespace: stakater-tronador
      key: username
  value_overrides:
    application:
      deployment:
        image:
          repository: {{APPLICATION_IMAGE_NAME}}
          tag: {{APPLICATION_IMAGE_TAG}}
